[project]
name = "obsidian-tag-tools"
version = "0.1.0"
description = "Extract tags from Obsidian vault markdown files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0",
    "click>=8.0",
]

[tool.setuptools]
packages = ["extractor", "parsers", "utils", "operations"]
py-modules = ["main"]

[project.scripts]
tagex = "main:cli"

[tool.uv]
package = true
