# Example Configuration for Tagex
#
# This file configures how tagex processes tags in your vault.
#
# SETUP:
# 1. Copy this file to your vault root as .tagex-config.yaml
# 2. Customize the settings for your vault's needs
# 3. Settings will be automatically loaded by tagex commands
#
# All settings are optional and have sensible defaults.

# Plural/Singular Preference
# Controls how tagex chooses between plural and singular tag variants
plural:
  # Preference mode:
  #   - usage: Prefer the most-used form (default)
  #   - plural: Always prefer plural forms (books, ideas, projects)
  #   - singular: Always prefer singular forms (book, idea, project)
  preference: usage

  # Usage ratio threshold (only applies when preference: usage)
  # A form must be used at least this many times more than alternatives
  # to be preferred. Default: 2.0
  #
  # Examples:
  #   - 2.0: "books" (10 uses) beats "book" (4 uses) → 10/4 = 2.5 ratio ✓
  #   - 2.0: "books" (10 uses) vs "book" (6 uses) → 10/6 = 1.67 ratio ✗
  #          (ratio too small, falls back to preference mode)
  usage_ratio_threshold: 2.0

# File and Directory Exclusions
# Controls which files and directories are excluded from processing
file_exclusions:
  # Exclude all dotfiles and dot-directories by default
  # This prevents processing of tool-specific directories like:
  #   .obsidian, .git, .trash, .vscode, .claude, .copilot, etc.
  exclude_dotfiles: true

  # Allowlist: specific dotfiles to include (when exclude_dotfiles is true)
  # Uncomment and add paths you want to process:
  include_dotfiles: []
  #   - .gitignore    # Example: process .gitignore file

  # Additional patterns to exclude (beyond dotfiles)
  # Glob patterns for files and directories to skip
  exclude_patterns: []
  #   - "templates/*"           # Exclude templates directory
  #   - "*.excalidraw.md"       # Exclude Excalidraw files
  #   - "archive/*"             # Exclude archive directory
  #   - "_drafts/*"             # Exclude drafts directory

# Similarity Detection
similarity:
  # Minimum similarity threshold for merge suggestions (0.0-1.0)
  threshold: 0.85
#
#   # Whether to use TF-IDF embeddings (requires scikit-learn)
#   use_embeddings: true

# Future Configuration Options
# (These are placeholders for future features)

# Tag Filtering
# filter:
#   # Minimum tag length to consider valid
#   min_length: 2
#
#   # Maximum tag length to consider valid
#   max_length: 50
#
#   # Patterns to exclude (regex)
#   exclude_patterns:
#     - '^temp-'
#     - '^draft-'

# Output Preferences
# output:
#   # Default output format (text, json, html)
#   format: text
#
#   # Maximum number of items to show in reports
#   max_items: 20
